PHOENIX-6076 Refactor Phoenix Hive Connectors introduced by PHOENIX-6057
apache/phoenix-connectors pull request #26
Opened 2020-08-14 08:45 UTC by richardantal

2020-08-14 13:20 UTC, stoty commented on phoenix-hive-base/src/main/java/org/apache/phoenix/hive/util/PhoenixStorageHandlerUtilBase.java
>  import java.io.ByteArrayInputStream;
Please mark the *Base classes abstract, to make sure no-one tries to instantiate them.

2020-08-14 13:23 UTC, stoty commented on phoenix-hive-base/src/main/java/org/apache/phoenix/hive/PhoenixSerializer.java
> +                        } else if (CompatUtil.DateAndTimestampSupport()){
Nice solution, but doesn't follow the java naming Conventions.
use .isDateAndTimeSupported() instead.

2020-08-14 13:23 UTC, stoty commented on phoenix-hive-base/src/main/java/org/apache/phoenix/hive/PhoenixSerializer.java
> +                            value = SpecificPhoenixSeriazer.GetValue(value);
Fix the typo while at it.

2020-08-14 13:25 UTC, stoty commented on phoenix-hive-base/pom.xml
> +            <plugin>
I think that in this case we simply want to depend on -base, instead of copying stuff from it.

2020-08-14 13:25 UTC, stoty commented on phoenix-hive-base/pom.xml
> +                        <configuration>
Probably depending on common would be better.

2020-08-14 13:26 UTC, stoty commented on phoenix-hive-base/pom.xml
> +        <netty.version>4.0.52.Final</netty.version>
These dependencies are pretty ancient.
Use the hive 3 dependency versions, if you can.

2020-08-14 13:28 UTC, stoty commented on phoenix-hive-base/phoenix5-hive/src/main/java/org/apache/phoenix/hive/SpecificPhoenixSeriazer.java
> +public class SpecificPhoenixSeriazer {
This is a pretty awkward name. 
Diff seems to be bit confused, but if this is a new class, try to find a better name for it.

2020-08-26 16:21 UTC, stoty commented
The java part basically looks good.

My problem is that we are building the code in the -common modules, when there is no reason to do that. (This applies both to hive and the rest of the connectors)

The -common modules should really just define the common dependencies, and have compiling/testing disabled.

You can base this on how it's done in Tephra.

2020-08-28 05:16 UTC, stoty requested changes
Almost there, I pointed out some minor nits.

2020-08-28 05:16 UTC, stoty commented on phoenix-hive-base/phoenix4-hive/src/main/java/org/apache/phoenix/compat/HiveCompatUtil.java
> +    public static Object GetDateOrTimestampValue(Object value){
Please keep to the Java naming conventions in new code (do not capitalize method names)

2020-08-28 05:16 UTC, stoty commented on phoenix4-compat/src/main/java/org/apache/phoenix/compat/CompatUtil.java
> +    public static boolean PHOENIX4ONLY = true;
I'd prefer

```
public static boolean isPhoenix4() {
    return true;
}
```
instead

2020-08-28 07:13 UTC, stoty approved these changes

2020-08-28 07:14 UTC, stoty commented
I'll wait for the checks to pass before committing

2020-08-28 07:15 UTC, richardantal commented
Thank you @stoty for your proper review (as always)! :)

2020-08-28 09:53 UTC, closed without merging